env:
  global:
    - CC_TEST_REPORTER_ID=c14b4c6794bb90d18bbed49361ffb8a7454d5a22075ba9b7d917702ddd838f3a
language: ruby
rvm:
 - 2.4.1
 
services:
  - postgresql
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:reset RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT  

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL